DROP INDEX public.inf_diario_fi_cnpj_fundo_pending_statistic_at_index;
DROP INDEX public.inf_diario_fi_cnpj_fundo_dt_comptc_index;
DROP INDEX public.investment_return_daily_dt_comptc_index;
DROP INDEX public.cota_hist_a_codneg_data_index;
